version: v3

volumes:
  db_vol:
    name: "postgres-vol"

services:
  # Postgres Container
  pg_db:
    container_name: PG-DB
    image: postgres:alpine3.19
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
      POSTGRES_DB: ${PG_DB}

  # App

  frontend:
    container_name: frontend-container
    image: fradriks/blog-frontend
    working_dir: /app/frontend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app/frontend
    ports:
      - 3000:3000
    # depends_on:
    #   - pg_db
