version: v3

volumes:
  db_vol:
    name: "postgres-vol"
  frontend-vol:

services:
  # Postgres Container
  pg_db:
    container_name: PG-DB
    image: postgres:alpine3.19
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
      POSTGRES_DB: ${PG_DB}
    env_file:
      - .env
  # App

  frontend:
    container_name: frontend-container
    image: fradriks/blog-frontend:1-slim
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - frontend-vol:/app
      - ./:/app-frontend
    ports:
      - 3000:3000
    depends_on:
      - pg_db
