apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-pod
  template:
    metadata:
      labels:
        app: frontend-pod

    spec:
      containers:
        - name: frontend-container
          image: fradriks/blog-frontend
          ports:
            - name: frontend-port
              containerPort: 3000
              protocol: TCP