apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql-pod
  type: ClusterIP
  ports:
    - name: postgres-service
      port: 5432
      targetPort: 5432
