name: BLOG'S WORKFLOW
run-name: Actions number ${{github.run_number}}

on:
  push:
    branches:
      - "main"

jobs:
  build_next_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4

      # - name: Login to docker hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{secrets.DOCKER_USERNAME}}
      #     password: ${{secrets.DOCKER_PWD}}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Push to Docker Hub
      #   uses : docker/build-push-action@v5

      - name: Test and Build an application
        run: |
          npm run build
          npm run lint
